# Generated by Django 3.2.9 on 2021-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=225),
        ),
    ]
